---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:

- name: basic-concourse-repo
  type: git
  source:
    uri: https://github.com/ebornier-pivotal/basic-concourse.git 

- name: cf-dev
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: dev 
    skip_cert_check: true

- name: cf-prod
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: prod 
    skip_cert_check: true

- name: basic-concourse-release
  type: github-release
  source:
    user: ebornier-pivotal 
    check: true
    repository: basic-concourse 
    include_source_tarball: true
    include_source_zip: true

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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 


jobs:


- name: deploy-basic-concourse 
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: basic-concourse-repo
    trigger: true
  - task: build
    file: basic-concourse-repo/ci/build.yml
  - put: cf-dev
    params:
      current_app_name: basic-concourse-dev
      manifest: basic-concourse-repo/manifest-dev.yml
      path: build/basic-concourse-0.0.1-SNAPSHOT.jar
  - put: slack-alert
    params:
      channel: '#circle-of-code'
      text: |
        The build had a result. Check it out at:
        https://concourse.cf.semea.piv/builds/$BUILD_ID
        The application is now available in development at https://basic-concourse-dev.cfapps.io


- name: deploy-basic-concourse-release
  public: true
  serial: true
  plan:
  - get: basic-concourse-repo
  - get: basic-concourse-release 
    trigger: true
    params:
      include_source_tarball: true
  - task: build
    file: basic-concourse-repo/ci/build-release.yml
  - put: cf-prod
    params:
      current_app_name: basic-concourse
      manifest: build/manifest-prod.yml
      path: build/basic-concourse-0.0.1-SNAPSHOT.jar
