---
resources:

- name: basic-concourse-repo
  type: git
  source:
    uri: https://github.com/ebornier-pivotal/basic-concourse.git 

- name: cf-dev
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: dev 
    skip_cert_check: true

- name: cf-prod
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: prod 
    skip_cert_check: true

- name: basic-concourse-release
  type: github-release
  source:
    user: ebornier-pivotal 
    repository: basic-concourse 
    include_source_tarball: true
    include_source_zip: true

jobs:


- name: deploy-basic-concourse 
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: basic-concourse-repo
    trigger: true
  - task: build
    file: basic-concourse-repo/ci/build.yml
  - put: cf-dev
    params:
      manifest: basic-concourse-repo/manifest.yml
      path: build/basic-concourse-0.0.1-SNAPSHOT.jar

- name: deploy-basic-concourse-release
  public: true
  serial: true
  plan:
  - get: basic-concourse-repo
  - get: basic-concourse-release 
    trigger: true
    params:
      include_source_tarball: true
  - task: build
    file: basic-concourse-repo/ci/build-release.yml
  - put: cf-prod
    params:
      manifest: build/manifest.yml
      path: build/basic-concourse-0.0.1-SNAPSHOT.jar
