---
resources:

- name: basic-concourse-repo
  type: git
  source:
    uri: https://github.com/ebornier-pivotal/basic-concourse.git 

- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

- name: basic-concourse-release
  type: github-release
  source:
    user: ebornier-pivotal
    repository: basic-concourse 
    include_source_tarball: true

jobs:


- name: deploy-basic-concourse 
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: basic-concourse-repo
    trigger: true
  - task: build
    file: basic-concourse-repo/ci/build.yml
  - put: cf
    params:
      manifest: basic-concourse-repo/manifest.yml
      path: build/basic-concourse-0.0.1-SNAPSHOT.jar

- name: deploy-basic-concourse-release
  public: true
  serial: true
  plan:
  - get: basic-concourse-release 
  - task: ls
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: "14.04"}
      inputs:
      - name: basic-concourse-release 
      run:
        path: ls
        args: ["-opR", "."]
